spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://dpg-cp0qvanjbltc73e25160-a.oregon-postgres.render.com/javacourse
    username: javacourse_user
    password: 5bPvoeQPF6EBMYblqBtxDBaivMQm7Ypb
    driver-class-name: org.postgresql.Driver
  session:
    store-type: jdbc
server:
  port: 8084

